/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary-fixed': '#001f25',
        'surface-container': '#dbf1fe',
        'on-secondary': '#ffffff',
        'surface-container-high': '#d5ecf8',
        'error-container': '#ffdad6',
        'on-primary': '#ffffff',
        'surface-bright': '#f3faff',
        'on-secondary-container': '#576867',
        'secondary-container': '#d4e6e5',
        primary: '#006673',
        'inverse-primary': '#6fd5e8',
        'on-secondary-fixed': '#0e1e1e',
        'on-error-container': '#93000a',
        error: '#ba1a1a',
        tertiary: '#266658',
        'inverse-surface': '#1e333c',
        'primary-fixed': '#a0efff',
        'outline-variant': '#bdc9cb',
        'on-error': '#ffffff',
        'on-tertiary-fixed': '#00201a',
        'tertiary-container': '#417f70',
        'on-surface-variant': '#3e494b',
        'on-primary-fixed-variant': '#004e59',
        'on-tertiary-fixed-variant': '#065043',
        'primary-container': '#008091',
        'tertiary-fixed-dim': '#94d3c1',
        'primary-fixed-dim': '#6fd5e8',
        secondary: '#516161',
        outline: '#6e797c',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed-variant': '#3a4a49',
        'on-primary-container': '#f8fdff',
        'on-tertiary': '#ffffff',
        'surface-container-low': '#e6f6ff',
        'secondary-fixed-dim': '#b8cac9',
        'on-background': '#071e27',
        'secondary-fixed': '#d4e6e5',
        'on-surface': '#071e27',
        'surface-dim': '#c7dde9',
        'surface-container-highest': '#cfe6f2',
        'on-tertiary-container': '#f4fffa',
        'surface-variant': '#cfe6f2',
        'tertiary-fixed': '#afefdd',
        background: '#f3faff',
        'surface-tint': '#006876',
        'inverse-on-surface': '#dff4ff',
        surface: '#f3faff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        md: '24px',
        base: '8px',
        xs: '4px',
        xl: '80px',
        gutter: '24px',
        sm: '12px',
        'margin-desktop': '64px',
        lg: '48px',
        'margin-mobile': '16px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        'body-md': ['Inter', 'sans-serif'],
        'headline-xl-mobile': ['Manrope', 'sans-serif'],
        'label-sm': ['JetBrains Mono', 'monospace'],
        'headline-md': ['Manrope', 'sans-serif'],
        'headline-lg': ['Manrope', 'sans-serif'],
        'headline-xl': ['Manrope', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'display-lg': ['Manrope', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-xl-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '800' }],
        'label-md': ['14px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
