<?php

namespace Database\Seeders;

use App\Models\Expert;
use Illuminate\Database\Seeder;

class ExpertSeeder extends Seeder
{
    public function run(): void
    {
        $experts = [
            [
                'slug' => 'dr-irman-firmansyah-s-hut-m-si',
                'name' => 'Dr. Irman Firmansyah, S.Hut, M.Si',
                'field' => 'Ahli Kehutanan & Tata Ruang',
                'kriteria' => 'Narasumber/Pembicara',
                'kriteria_list' => ['Narasumber/Pembicara', 'Instruktur Pengajar'],
                'location' => 'Bogor',
                'lat' => -6.5622,
                'lng' => 106.7297,
                'rating' => 4.9,
                'photo' => 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=200',
                'cover' => 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&q=80&w=1400',
                'verified' => true,
                'featured' => true,
                'institution' => 'PSL - IPB University',
                'active_since' => 2011,
                'email' => 'irmanf@gmail.com',
                'keahlian' => ['Ilmu Kehutanan', 'Ilmu Lingkungan', 'System Dynamics', 'Spasial Dynamics'],
                'alamat_lengkap' => 'Komplek IPB 2, Blok C No. 4 Sindang Barang, Bogor 16117',
                'alamat_kota' => 'Kota Bogor',
                'alamat_provinsi' => 'Jawa Barat',
                'lokasi_label' => 'Jl. Mercurius No.4, RW.5, Ciherang, Kec. Dramaga, Kabupaten Bogor, Jawa Barat 16680',
                'sosial' => [
                    ['label' => 'Instagram', 'type' => 'instagram', 'url' => 'https://www.instagram.com/dr.irman/'],
                    ['label' => 'Facebook', 'type' => 'facebook', 'url' => 'https://www.facebook.com/wearecase27/'],
                    ['label' => 'YouTube', 'type' => 'youtube', 'url' => 'https://www.youtube.com/channel/UCva2ULajnzEhorlabr_yDpA'],
                    ['label' => 'Twitter', 'type' => 'twitter', 'url' => 'https://twitter.com/collective27'],
                ],
                'narasumber_riwayat' => [
                    [
                        'title' => 'Identifikasi materi KRP & analisis pengaruh KLHS RDTR Kec. Selaawi–Banyuresmi',
                        'penyelenggara' => 'Dinas Lingkungan Hidup Kab. Garut',
                        'tempat' => 'Garut',
                        'tanggal' => '15 Nov 2022',
                    ],
                    [
                        'title' => 'Penyepakatan isu pembangunan berkelanjutan strategis KLHS RDTR Kec. Selaawi–Banyuresmi',
                        'penyelenggara' => 'Dinas Lingkungan Hidup Kab. Garut',
                        'tempat' => 'Garut',
                        'tanggal' => '21 Sep 2022',
                    ],
                ],
                'kajian_riwayat' => [
                    [
                        'title' => 'Kajian sistem dinamik untuk KLHS RPJMD Kota Manado',
                        'tempat' => 'Manado',
                        'tanggal' => 'Jun–Agt 2021',
                    ],
                ],
            ],
            [
                'slug' => 'ir-nurul-hidayah-m-t',
                'name' => 'Ir. Nurul Hidayah, M.T.',
                'field' => 'Ahli Kualitas Udara & Kebisingan',
                'kriteria' => 'Narasumber/Pembicara',
                'kriteria_list' => ['Narasumber/Pembicara'],
                'location' => 'Depok',
                'lat' => -6.4025,
                'lng' => 106.7942,
                'rating' => 4.7,
                'photo' => 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=100',
                'cover' => 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&q=80&w=800',
                'verified' => true,
                'featured' => false,
                'institution' => 'Universitas Indonesia',
                'active_since' => 2015,
                'email' => 'nurul.hidayah@example.com',
                'keahlian' => ['Kualitas Udara', 'Kebisingan Lingkungan'],
                'alamat_kota' => 'Depok',
                'alamat_provinsi' => 'Jawa Barat',
                'lokasi_label' => 'Depok, Jawa Barat',
                'sosial' => [],
                'narasumber_riwayat' => [],
                'kajian_riwayat' => [],
            ],
            [
                'slug' => 'dr-agus-purnomo-s-si-m-env',
                'name' => 'Dr. Agus Purnomo, S.Si, M.Env',
                'field' => 'Ahli Hidrologi & Kualitas Air',
                'kriteria' => 'Narasumber/Pembicara',
                'kriteria_list' => ['Narasumber/Pembicara'],
                'location' => 'Jakarta',
                'lat' => -6.2088,
                'lng' => 106.8456,
                'rating' => 5.0,
                'photo' => 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=100',
                'cover' => 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&q=80&w=800',
                'verified' => false,
                'featured' => false,
                'institution' => 'Universitas Indonesia',
                'active_since' => 2018,
                'email' => 'agus.purnomo@example.com',
                'keahlian' => ['Hidrologi', 'Kualitas Air'],
                'alamat_kota' => 'Jakarta',
                'alamat_provinsi' => 'DKI Jakarta',
                'lokasi_label' => 'Jakarta',
                'sosial' => [],
                'narasumber_riwayat' => [],
                'kajian_riwayat' => [],
            ],
            [
                'slug' => 'dr-andi-prasetyo-m-pd',
                'name' => 'Dr. Andi Prasetyo, M.Pd.',
                'field' => 'Instruktur Pelatihan Kepemimpinan',
                'kriteria' => 'Instruktur Pengajar',
                'kriteria_list' => ['Instruktur Pengajar'],
                'location' => 'Bandung',
                'lat' => -6.9175,
                'lng' => 107.6191,
                'rating' => 4.8,
                'photo' => 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=100',
                'cover' => 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&q=80&w=800',
                'verified' => true,
                'featured' => false,
                'institution' => 'Universitas Pendidikan Indonesia',
                'active_since' => 2013,
                'email' => 'andi.prasetyo@example.com',
                'keahlian' => ['Kepemimpinan', 'Pelatihan Manajemen'],
                'alamat_kota' => 'Bandung',
                'alamat_provinsi' => 'Jawa Barat',
                'lokasi_label' => 'Bandung, Jawa Barat',
                'sosial' => [],
                'narasumber_riwayat' => [],
                'kajian_riwayat' => [],
            ],
            [
                'slug' => 'dra-ratna-kusuma-m-si',
                'name' => 'Dra. Ratna Kusuma, M.Si.',
                'field' => 'Instruktur Pengembangan Kurikulum',
                'kriteria' => 'Instruktur Pengajar',
                'kriteria_list' => ['Instruktur Pengajar'],
                'location' => 'Semarang',
                'lat' => -6.9932,
                'lng' => 110.4203,
                'rating' => 4.6,
                'photo' => 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=100',
                'cover' => 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&q=80&w=800',
                'verified' => true,
                'featured' => false,
                'institution' => 'Universitas Diponegoro',
                'active_since' => 2016,
                'email' => 'ratna.kusuma@example.com',
                'keahlian' => ['Pengembangan Kurikulum', 'Pendidikan'],
                'alamat_kota' => 'Semarang',
                'alamat_provinsi' => 'Jawa Tengah',
                'lokasi_label' => 'Semarang, Jawa Tengah',
                'sosial' => [],
                'narasumber_riwayat' => [],
                'kajian_riwayat' => [],
            ],
            [
                'slug' => 'drs-yusuf-hidayat-m-m',
                'name' => 'Drs. Yusuf Hidayat, M.M.',
                'field' => 'Instruktur Manajemen & Kewirausahaan',
                'kriteria' => 'Instruktur Pengajar',
                'kriteria_list' => ['Instruktur Pengajar'],
                'location' => 'Surabaya',
                'lat' => -7.2575,
                'lng' => 112.7521,
                'rating' => 4.9,
                'photo' => 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=100',
                'cover' => 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&q=80&w=800',
                'verified' => false,
                'featured' => false,
                'institution' => 'Universitas Airlangga',
                'active_since' => 2014,
                'email' => 'yusuf.hidayat@example.com',
                'keahlian' => ['Manajemen', 'Kewirausahaan'],
                'alamat_kota' => 'Surabaya',
                'alamat_provinsi' => 'Jawa Timur',
                'lokasi_label' => 'Surabaya, Jawa Timur',
                'sosial' => [],
                'narasumber_riwayat' => [],
                'kajian_riwayat' => [],
            ],
        ];

        foreach ($experts as $expert) {
            Expert::updateOrCreate(['slug' => $expert['slug']], $expert);
        }
    }
}
